export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'USERS_LOGIN_FAILURE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_ERROR = 'GET_ERROR';
export const GET_PROFILE = 'GET_PROFILE';
